[env:esp32-c6-lcd-1_47]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = qio
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
lib_deps =
  moononournation/GFX Library for Arduino@^1.5.6
  tzapu/WiFiManager@^2.0.17
